/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DillanAsbury
 */
public class EmployeeData extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeData
     */
    public EmployeeData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        findEmployee = new javax.swing.JButton();
        addEmployee = new javax.swing.JButton();
        employeeDataSytem = new javax.swing.JLabel();
        panelAddEmployee = new javax.swing.JPanel();
        hourlyButton = new javax.swing.JButton();
        commissionedButton = new javax.swing.JButton();
        salariedButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        backButtSelEmpPan = new javax.swing.JButton();
        panelHourly = new javax.swing.JPanel();
        backButtHourPan = new javax.swing.JButton();
        panelCommissioned = new javax.swing.JPanel();
        backButtonCommPan = new javax.swing.JButton();
        panelSalaried = new javax.swing.JPanel();
        backButtSalPan = new javax.swing.JButton();
        panelFindEmployee = new javax.swing.JPanel();
        searchBar = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        findEmployee.setText("Find Employee");
        findEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findEmployeeActionPerformed(evt);
            }
        });
        panelMenu.add(findEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 260, 120));

        addEmployee.setText("Add Employee");
        addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeActionPerformed(evt);
            }
        });
        panelMenu.add(addEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 260, 120));

        employeeDataSytem.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        employeeDataSytem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeDataSytem.setText("EMPLOYEE DATA SYSTEM");
        employeeDataSytem.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        employeeDataSytem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMenu.add(employeeDataSytem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 180));

        getContentPane().add(panelMenu, "card4");

        panelAddEmployee.setPreferredSize(new java.awt.Dimension(796, 470));
        panelAddEmployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hourlyButton.setText("HOURLY");
        hourlyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyButtonActionPerformed(evt);
            }
        });
        panelAddEmployee.add(hourlyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 230, 307));

        commissionedButton.setBackground(new java.awt.Color(255, 255, 255));
        commissionedButton.setText("COMMISSIONED");
        commissionedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commissionedButtonActionPerformed(evt);
            }
        });
        panelAddEmployee.add(commissionedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 230, 307));

        salariedButton.setText("SALARIED");
        salariedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salariedButtonActionPerformed(evt);
            }
        });
        panelAddEmployee.add(salariedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 230, 307));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT AN EMPLOYEE TYPE");
        panelAddEmployee.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 160));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        panelAddEmployee.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 770, -1));

        backButtSelEmpPan.setText("BACK");
        backButtSelEmpPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtSelEmpPanActionPerformed(evt);
            }
        });
        panelAddEmployee.add(backButtSelEmpPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelAddEmployee, "card3");

        panelHourly.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButtHourPan.setText("BACK");
        backButtHourPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtHourPanActionPerformed(evt);
            }
        });
        panelHourly.add(backButtHourPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelHourly, "card5");

        panelCommissioned.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButtonCommPan.setText("BACK");
        backButtonCommPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonCommPanActionPerformed(evt);
            }
        });
        panelCommissioned.add(backButtonCommPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelCommissioned, "card7");

        panelSalaried.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButtSalPan.setText("BACK");
        backButtSalPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtSalPanActionPerformed(evt);
            }
        });
        panelSalaried.add(backButtSalPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelSalaried, "card6");

        panelFindEmployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        panelFindEmployee.add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 193, 678, 40));

        searchButton.setText("Search");
        panelFindEmployee.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 140, -1));

        jLabel2.setText("ENTER EMPLOYEE ID NUMBER:");
        panelFindEmployee.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 220, -1));

        jButton2.setText("BACK");
        panelFindEmployee.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        getContentPane().add(panelFindEmployee, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeActionPerformed
        panelAddEmployee.setVisible(true);
        panelMenu.setVisible(false);
    }//GEN-LAST:event_addEmployeeActionPerformed

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void findEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findEmployeeActionPerformed
        panelFindEmployee.setVisible(true);
        panelMenu.setVisible(false);
    }//GEN-LAST:event_findEmployeeActionPerformed

    private void backButtSelEmpPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtSelEmpPanActionPerformed
        panelAddEmployee.setVisible(false);
        panelMenu.setVisible(true);
    }//GEN-LAST:event_backButtSelEmpPanActionPerformed

    private void hourlyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyButtonActionPerformed
        panelHourly.setVisible(true);
        panelAddEmployee.setVisible(false);
    }//GEN-LAST:event_hourlyButtonActionPerformed

    private void commissionedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commissionedButtonActionPerformed
        panelCommissioned.setVisible(true);
        panelAddEmployee.setVisible(false);
    }//GEN-LAST:event_commissionedButtonActionPerformed

    private void salariedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salariedButtonActionPerformed
        panelSalaried.setVisible(true);
        panelAddEmployee.setVisible(false);
    }//GEN-LAST:event_salariedButtonActionPerformed

    private void backButtHourPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtHourPanActionPerformed
        panelHourly.setVisible(false);
        panelAddEmployee.setVisible(true);
    }//GEN-LAST:event_backButtHourPanActionPerformed

    private void backButtonCommPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonCommPanActionPerformed
        panelCommissioned.setVisible(false);
        panelAddEmployee.setVisible(true);
    }//GEN-LAST:event_backButtonCommPanActionPerformed

    private void backButtSalPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtSalPanActionPerformed
        panelSalaried.setVisible(false);
        panelAddEmployee.setVisible(true);
    }//GEN-LAST:event_backButtSalPanActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployee;
    private javax.swing.JButton backButtHourPan;
    private javax.swing.JButton backButtSalPan;
    private javax.swing.JButton backButtSelEmpPan;
    private javax.swing.JButton backButtonCommPan;
    private javax.swing.JButton commissionedButton;
    private javax.swing.JLabel employeeDataSytem;
    private javax.swing.JButton findEmployee;
    private javax.swing.JButton hourlyButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelAddEmployee;
    private javax.swing.JPanel panelCommissioned;
    private javax.swing.JPanel panelFindEmployee;
    private javax.swing.JPanel panelHourly;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelSalaried;
    private javax.swing.JButton salariedButton;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
